### ISSUE TITLE
明日复明日，明日何其多……安装方法还没出

### ISSUE THREAD

**Issue by Rongronggg9** [ACGunion/openshift-php7#1]
而且www.51acg.gq/openshift-php7.html也无法访问了呢

**Comment by ACGunion** [comment]
按照wiki上的步骤理论上可以安装，安装完之后要自己修改PHP-FPM的配置文件。安装过程中有问题欢迎继续反馈。

**Comment by Rongronggg9** [comment]
好的

**Comment by Rongronggg9** [comment]
http://ww4.sinaimg.cn/large/d46786adjw1f0e3fmabfzj20ir0btae9.jpg
看图……
有点醉

**Comment by ACGunion** [comment]
已经改了。您直接用qq联系我吧。falcomaa@qq.com

**Comment by Rongronggg9** [comment]
猴
